#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent passwd apt-blitz > /dev/null 2>&1; then
            adduser --system --group --quiet --no-create-home \
                --home /var/cache/apt-blitz \
                apt-blitz
        fi

        if [ ! -d /run/systemd/system ] && [ -x /etc/init.d/apt-blitz ]; then
            update-rc.d apt-blitz defaults >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
