#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent passwd apt-blitz > /dev/null 2>&1; then
            adduser --system --group --quiet --no-create-home \
                --home /var/cache/apt-blitz \
                apt-blitz
        fi
        ;;
esac

#DEBHELPER#

exit 0
